### ISSUE TITLE
Add `query` implementation for listing blocks in a store

### ISSUE THREAD

**Issue by michaelsbradleyjr** [codex-storage/nim-datastore#8]

**Comment by Bulat-Ziganshin** [comment]
Just now all we need is to support `select id from Store` statement.

Later, Dmitry wants to save Manifests to DB too, so we will probably need to make composed Key (`"Manifest" / id` or `"Block" / id`) and select ids corresponding to one domain (`where id LIKE "Manifest*"`).

**Comment by dryajov** [comment]
Just to note that we do want to support the full range of query capabilities that other datastores expose, but we can do this in steps.
